import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface) => {
    return queryInterface.bulkInsert("courses", [
      {
        id: 1,
        title: "Giao Dịch Vàng Phái Sinh (XAU/USD) Từ A-Z",
        desc: "Khóa học chuyên sâu về giao dịch Vàng (Gold Trading). Hướng dẫn phân tích cơ bản, kỹ thuật, quản lý vốn và tâm lý giao dịch để kiếm lợi nhuận bền vững từ thị trường Vàng.",
        image: "https://res.cloudinary.com/dq4basktt/image/upload/v1768372834/tech-global/courses/yum2ffrcd7ptkncunw16.png",
        category: "Gold Trading",
        level: "Beginner",
        lessons_count: 10,
        price: 2500000,
        discount: 30,
        slug: "giao-dich-vang-phai-sinh-tu-a-z",
        status: "published",
        video_demo: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
        duration: "15h 30m",
        rating: 4.9,
        students: 2100,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        title: "Đầu Tư Crypto & Blockchain Toàn Tập",
        desc: "Hiểu rõ về công nghệ Blockchain, Bitcoin, Ethereum và thị trường tiền mã hóa. Hướng dẫn cách đầu tư, trade coin, staking, farming và quản lý rủi ro trong thị trường Crypto.",
        image:
          "https://res.cloudinary.com/dq4basktt/image/upload/v1768372694/tech-global/courses/kalfqra8n6p7kjaagjqg.jpg",
        category: "Crypto",
        level: "Intermediate",
        lessons_count: 15,
        price: 3000000,
        discount: 15,
        slug: "dau-tu-crypto-blockchain-toan-tap",
        status: "published",
        video_demo: "https://www.youtube.com/watch?v=z2f7RHgvddc",
        duration: "30h 00m",
        rating: 4.8,
        students: 1800,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        title: "Phân Tích Kỹ Thuật Thực Chiến (Gold & Crypto)",
        desc: "Làm chủ các công cụ phân tích kỹ thuật: Candlestick, Support/Resistance, Trendline, Fibonacci, RSI, MACD, Elliott Wave. Áp dụng thực chiến trên biểu đồ Vàng và Crypto.",
        image:
          "https://res.cloudinary.com/dq4basktt/image/upload/v1768372582/tech-global/courses/mtgjhkbzcxggotiw4bbv.jpg",
        category: "Trading Analysis",
        level: "Advanced",
        lessons_count: 20,
        price: 4500000,
        discount: 0,
        slug: "phan-tich-ky-thuat-thuc-chien",
        status: "published",
        video_demo: "https://www.youtube.com/watch?v=R6plN3FvzFY",
        duration: "40h 00m",
        rating: 5.0,
        students: 950,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        title: "Giao Dịch Crypto Từ A-Z",
        desc: "Khóa học chuyên sâu về giao dịch Crypto. Hướng dẫn phân tích cơ bản, kỹ thuật, quản lý vốn và tâm lý giao dịch để kiếm lợi nhuận bền vững từ thị trường Crypto.",
        image:
          "https://res.cloudinary.com/dq4basktt/image/upload/v1768372392/tech-global/courses/lcooru0dvlepvxiye6oq.png",
        category: "Crypto",
        level: "Beginner",
        lessons_count: 10,
        price: 100,
        discount: 0,
        slug: "giao-dich-crypto-tu-a-z",
        status: "published",
        video_demo: "https://www.youtube.com/watch?v=M62l1xA5Eu8",
        duration: "15h 30m",
        rating: 4.9,
        students: 2100,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  down: async (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete("courses", {}, {});
  },
};
