import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface) => {
    const now = new Date();
    const studies = [
      {
        section_id: 12,
        type: "multiple-choice",
        content: "CPI cao thường:",
        options: JSON.stringify([
          {
            id: "opt-12-1-0",
            text: "Tăng kỳ vọng lãi suất, USD mạnh",
            isCorrect: true,
          },
          { id: "opt-12-1-1", text: "USD yếu", isCorrect: false },
          { id: "opt-12-1-2", text: "Không ảnh hưởng", isCorrect: false },
          { id: "opt-12-1-3", text: "Vàng tăng ngay", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Tăng kỳ vọng lãi suất, USD mạnh". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "multiple-choice",
        content: "NFP tốt thường:",
        options: JSON.stringify([
          {
            id: "opt-12-2-0",
            text: "Củng cố USD và thắt chặt chính sách",
            isCorrect: true,
          },
          { id: "opt-12-2-1", text: "USD yếu", isCorrect: false },
          { id: "opt-12-2-2", text: "Vàng tăng mạnh", isCorrect: false },
          { id: "opt-12-2-3", text: "Crypto giảm luôn", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Củng cố USD và thắt chặt chính sách". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "multiple-choice",
        content: "Quyết định lãi suất Fed:",
        options: JSON.stringify([
          {
            id: "opt-12-3-0",
            text: "Điều hướng dòng tiền toàn cầu",
            isCorrect: true,
          },
          { id: "opt-12-3-1", text: "Chỉ ảnh hưởng crypto", isCorrect: false },
          { id: "opt-12-3-2", text: "Chỉ ảnh hưởng vàng", isCorrect: false },
          { id: "opt-12-3-3", text: "Không ảnh hưởng", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Điều hướng dòng tiền toàn cầu". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "multiple-choice",
        content: "PMI phản ánh:",
        options: JSON.stringify([
          {
            id: "opt-12-4-0",
            text: "Sức khỏe sản xuất/dịch vụ",
            isCorrect: true,
          },
          { id: "opt-12-4-1", text: "Lạm phát", isCorrect: false },
          { id: "opt-12-4-2", text: "Nợ công", isCorrect: false },
          { id: "opt-12-4-3", text: "Tỷ giá", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Sức khỏe sản xuất/dịch vụ". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "multiple-choice",
        content: "Giao dịch quanh tin lớn:",
        options: JSON.stringify([
          {
            id: "opt-12-5-0",
            text: "Tránh vào trước tin, chờ retest theo hướng",
            isCorrect: true,
          },
          { id: "opt-12-5-1", text: "Vào đúng lúc công bố", isCorrect: false },
          { id: "opt-12-5-2", text: "Đoán số liệu", isCorrect: false },
          { id: "opt-12-5-3", text: "Không SL", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Tránh vào trước tin, chờ retest theo hướng". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "essay",
        content: "Kịch bản sau CPI cao hơn kỳ vọng.",
        options: null,
        media: null,
        correct_answer:
          "USD mạnh, vàng chịu áp lực; chờ retest kháng cự mới để sell theo cấu trúc.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "essay",
        content: "Phản ứng sau NFP bất ngờ tốt.",
        options: null,
        media: null,
        correct_answer:
          "Biến động mạnh; chờ ổn định; trade retest theo hướng chủ đạo.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "essay",
        content: "Theo dõi DXY và vàng.",
        options: null,
        media: null,
        correct_answer:
          "DXY tăng gây áp lực vàng; chọn kịch bản phù hợp; tránh giao dịch trước tin.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "essay",
        content: "Tin bất ngờ trong phiên Mỹ.",
        options: null,
        media: null,
        correct_answer:
          "Giảm khối lượng, không gỡ lỗ; chờ cấu trúc mới để đánh giá.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "essay",
        content: "Xây checklist giao dịch theo tin.",
        options: null,
        media: null,
        correct_answer:
          "Lịch tin, kịch bản phản ứng, quản trị rủi ro, xác nhận kỹ thuật, đánh giá sau tin.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "case-study",
        content: "Phân tích CPI cao và tác động tức thì lên USD.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "USD mạnh, ưu tiên sell vàng tại kháng cự sau retest có xác nhận.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "case-study",
        content: "NFP tốt, giá biến động mạnh: chọn điểm vào an toàn.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Chờ ổn định và retest theo hướng chủ đạo, SL theo cấu trúc.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "case-study",
        content: "Theo dõi DXY tăng và áp lực lên vàng.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Ưu tiên sell vàng tại retest kháng cự, tránh vào trước tin.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "case-study",
        content: "Tin bất ngờ trong phiên Mỹ và xử lý tâm lý giao dịch.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Giảm khối lượng, chờ cấu trúc mới rõ ràng, không gỡ lỗ vô kỷ luật.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 12,
        type: "case-study",
        content: "Checklist giao dịch theo lịch tin và confluence kỹ thuật.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Chuẩn bị kịch bản, quản trị rủi ro, xác nhận kỹ thuật trước khi vào lệnh.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "multiple-choice",
        content: "CPI cao thường:",
        options: JSON.stringify([
          {
            id: "opt-15-1-0",
            text: "Tăng kỳ vọng lãi suất, USD mạnh",
            isCorrect: true,
          },
          { id: "opt-15-1-1", text: "USD yếu", isCorrect: false },
          { id: "opt-15-1-2", text: "Không ảnh hưởng", isCorrect: false },
          { id: "opt-15-1-3", text: "Vàng tăng ngay", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Tăng kỳ vọng lãi suất, USD mạnh". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "multiple-choice",
        content: "NFP tốt thường:",
        options: JSON.stringify([
          {
            id: "opt-15-2-0",
            text: "Củng cố USD và thắt chặt chính sách",
            isCorrect: true,
          },
          { id: "opt-15-2-1", text: "USD yếu", isCorrect: false },
          { id: "opt-15-2-2", text: "Vàng tăng mạnh", isCorrect: false },
          { id: "opt-15-2-3", text: "Crypto giảm luôn", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Củng cố USD và thắt chặt chính sách". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "multiple-choice",
        content: "Quyết định lãi suất Fed:",
        options: JSON.stringify([
          {
            id: "opt-15-3-0",
            text: "Điều hướng dòng tiền toàn cầu",
            isCorrect: true,
          },
          { id: "opt-15-3-1", text: "Chỉ ảnh hưởng crypto", isCorrect: false },
          { id: "opt-15-3-2", text: "Chỉ ảnh hưởng vàng", isCorrect: false },
          { id: "opt-15-3-3", text: "Không ảnh hưởng", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Điều hướng dòng tiền toàn cầu". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "multiple-choice",
        content: "PMI phản ánh:",
        options: JSON.stringify([
          {
            id: "opt-15-4-0",
            text: "Sức khỏe sản xuất/dịch vụ",
            isCorrect: true,
          },
          { id: "opt-15-4-1", text: "Lạm phát", isCorrect: false },
          { id: "opt-15-4-2", text: "Nợ công", isCorrect: false },
          { id: "opt-15-4-3", text: "Tỷ giá", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Sức khỏe sản xuất/dịch vụ". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "multiple-choice",
        content: "Giao dịch quanh tin lớn:",
        options: JSON.stringify([
          {
            id: "opt-15-5-0",
            text: "Tránh vào trước tin, chờ retest theo hướng",
            isCorrect: true,
          },
          { id: "opt-15-5-1", text: "Vào đúng lúc công bố", isCorrect: false },
          { id: "opt-15-5-2", text: "Đoán số liệu", isCorrect: false },
          { id: "opt-15-5-3", text: "Không SL", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Giải thích chi tiết: Đáp án đúng là "Tránh vào trước tin, chờ retest theo hướng". Đây là kiến thức quan trọng cần nắm vững trong phần Tin tức & vĩ mô.',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "essay",
        content: "Kịch bản sau CPI cao hơn kỳ vọng.",
        options: null,
        media: null,
        correct_answer:
          "USD mạnh, vàng chịu áp lực; chờ retest kháng cự mới để sell theo cấu trúc.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "essay",
        content: "Phản ứng sau NFP bất ngờ tốt.",
        options: null,
        media: null,
        correct_answer:
          "Biến động mạnh; chờ ổn định; trade retest theo hướng chủ đạo.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "essay",
        content: "Theo dõi DXY và vàng.",
        options: null,
        media: null,
        correct_answer:
          "DXY tăng gây áp lực vàng; chọn kịch bản phù hợp; tránh giao dịch trước tin.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "essay",
        content: "Tin bất ngờ trong phiên Mỹ.",
        options: null,
        media: null,
        correct_answer:
          "Giảm khối lượng, không gỡ lỗ; chờ cấu trúc mới để đánh giá.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "essay",
        content: "Xây checklist giao dịch theo tin.",
        options: null,
        media: null,
        correct_answer:
          "Lịch tin, kịch bản phản ứng, quản trị rủi ro, xác nhận kỹ thuật, đánh giá sau tin.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "case-study",
        content: "Phân tích CPI cao và tác động tức thì lên USD.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "USD mạnh, ưu tiên sell vàng tại kháng cự sau retest có xác nhận.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "case-study",
        content: "NFP tốt, giá biến động mạnh: chọn điểm vào an toàn.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Chờ ổn định và retest theo hướng chủ đạo, SL theo cấu trúc.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "case-study",
        content: "Theo dõi DXY tăng và áp lực lên vàng.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Ưu tiên sell vàng tại retest kháng cự, tránh vào trước tin.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "case-study",
        content: "Tin bất ngờ trong phiên Mỹ và xử lý tâm lý giao dịch.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Giảm khối lượng, chờ cấu trúc mới rõ ràng, không gỡ lỗ vô kỷ luật.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 15,
        type: "case-study",
        content: "Checklist giao dịch theo lịch tin và confluence kỹ thuật.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Chuẩn bị kịch bản, quản trị rủi ro, xác nhận kỹ thuật trước khi vào lệnh.",
        explanation:
          "Phân tích đa khung, kiểm chứng confluence và nến xác nhận.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 1,
        type: "multiple-choice",
        content: "BOS (Break of Structure) là:",
        options: JSON.stringify([
          {
            id: "opt-1-1-0",
            text: "Phá vỡ đỉnh/đáy xu hướng hiện tại",
            isCorrect: true,
          },
          { id: "opt-1-1-1", text: "Nến Doji xuất hiện", isCorrect: false },
          {
            id: "opt-1-1-2",
            text: "Khối lượng tăng đột biến",
            isCorrect: false,
          },
          { id: "opt-1-1-3", text: "Giá tạo gap", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Phá vỡ đỉnh/đáy xu hướng hiện tại".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 1,
        type: "multiple-choice",
        content: "CHoCH báo hiệu:",
        options: JSON.stringify([
          {
            id: "opt-1-2-0",
            text: "Khả năng chuyển pha xu hướng",
            isCorrect: true,
          },
          {
            id: "opt-1-2-1",
            text: "Tiếp diễn xu hướng hiện tại",
            isCorrect: false,
          },
          {
            id: "opt-1-2-2",
            text: "Tăng biến động trong phiên",
            isCorrect: false,
          },
          {
            id: "opt-1-2-3",
            text: "Mở rộng biên độ dao động",
            isCorrect: false,
          },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Khả năng chuyển pha xu hướng".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 1,
        type: "essay",
        content: "Xác định FVG và vùng rebalancing.",
        options: null,
        media: null,
        correct_answer:
          "Kỳ vọng giá lấp FVG; vào khi có nến xác nhận tại retest.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 1,
        type: "case-study",
        content: "Sweep đỉnh và entry sau sweep.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Đợi nến xác nhận đảo chiều tại OB; vào sau pullback ngắn; SL qua đỉnh sweep.",
        explanation: "Ưu tiên entry tại vùng có confluence.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 2,
        type: "multiple-choice",
        content: "Engulfing là:",
        options: JSON.stringify([
          {
            id: "opt-2-1-0",
            text: "Nến sau bao trùm hoàn toàn nến trước",
            isCorrect: true,
          },
          {
            id: "opt-2-1-1",
            text: "Nến trong thân nến trước",
            isCorrect: false,
          },
          {
            id: "opt-2-1-2",
            text: "Hai nến có đỉnh/đáy bằng nhau",
            isCorrect: false,
          },
          { id: "opt-2-1-3", text: "Nến không bóng", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Nến sau bao trùm hoàn toàn nến trước".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 2,
        type: "multiple-choice",
        content: "Doji phản ánh:",
        options: JSON.stringify([
          { id: "opt-2-2-0", text: "Giằng co, thiếu cam kết", isCorrect: true },
          { id: "opt-2-2-1", text: "Đảo chiều chắc chắn", isCorrect: false },
          { id: "opt-2-2-2", text: "Momentum mạnh", isCorrect: false },
          { id: "opt-2-2-3", text: "Breakout", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Giằng co, thiếu cam kết".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 2,
        type: "essay",
        content: "Morning Star tại vùng cầu HTF: kế hoạch vào lệnh.",
        options: null,
        media: null,
        correct_answer:
          "Xác nhận bằng nến thứ ba; buy tại retest; SL dưới đáy cụm; TP vùng kháng cự kế.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 2,
        type: "case-study",
        content: "Bearish Engulfing ở đỉnh kháng cự.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Sell sau retest nhỏ; SL trên đỉnh cụm; TP vùng hỗ trợ gần.",
        explanation: "Xác nhận tại vùng kháng cự có confluence.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 3,
        type: "multiple-choice",
        content: "S/R là:",
        options: JSON.stringify([
          {
            id: "opt-3-1-0",
            text: "Vùng giá nơi cung/cầu trội",
            isCorrect: true,
          },
          { id: "opt-3-1-1", text: "Chỉ báo momentum", isCorrect: false },
          { id: "opt-3-1-2", text: "Mức Fibo cố định", isCorrect: false },
          { id: "opt-3-1-3", text: "Mẫu nến", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Vùng giá nơi cung/cầu trội".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 3,
        type: "multiple-choice",
        content: "Retest hợp lệ là:",
        options: JSON.stringify([
          {
            id: "opt-3-2-0",
            text: "Phá vùng rồi quay lại kiểm định có xác nhận",
            isCorrect: true,
          },
          {
            id: "opt-3-2-1",
            text: "Quay lại vùng nhiều lần",
            isCorrect: false,
          },
          { id: "opt-3-2-2", text: "Nến Doji tại vùng", isCorrect: false },
          { id: "opt-3-2-3", text: "RSI vượt 50", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation:
          'Đáp án đúng: "Phá vùng rồi quay lại kiểm định có xác nhận".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 3,
        type: "essay",
        content: "False-break hỗ trợ với sweep đáy.",
        options: null,
        media: null,
        correct_answer:
          "Vào buy sau sweep khi giá quay lại vùng; SL dưới đáy sweep; TP vùng kháng cự.",
        explanation: null,
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 3,
        type: "case-study",
        content: "Range rõ ràng: chiến lược giao dịch.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Mua biên dưới, bán biên trên với tín hiệu nến; tránh giữa range.",
        explanation: "Khai thác biên của vùng tích luỹ.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 4,
        type: "multiple-choice",
        content: "Break trendline hợp lệ khi:",
        options: JSON.stringify([
          {
            id: "opt-4-2-0",
            text: "Đóng cửa rõ ngoài và có follow-through",
            isCorrect: true,
          },
          { id: "opt-4-2-1", text: "Có Doji", isCorrect: false },
          { id: "opt-4-2-2", text: "RSI 70", isCorrect: false },
          { id: "opt-4-2-3", text: "MACD giao cắt", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Đóng cửa rõ ngoài và có follow-through".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 4,
        type: "case-study",
        content: "Chạm trendline lần 3 trong xu hướng tăng.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer: "Buy với nến xác nhận; SL dưới swing; TP đỉnh kênh.",
        explanation: "Ưu tiên điểm chạm thứ ba.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 5,
        type: "multiple-choice",
        content: "Mục tiêu extension thường dùng:",
        options: JSON.stringify([
          { id: "opt-5-2-0", text: "1.272/1.618", isCorrect: true },
          { id: "opt-5-2-1", text: "0.382", isCorrect: false },
          { id: "opt-5-2-2", text: "0.5", isCorrect: false },
          { id: "opt-5-2-3", text: "3.0", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "1.272/1.618".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 5,
        type: "case-study",
        content: "AB=CD hoàn tất tại vùng kháng cự.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer: "Sell tại điểm D; SL trên vùng; TP hỗ trợ gần.",
        explanation: "Kiểm chứng vùng và cấu trúc trước entry.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 6,
        type: "multiple-choice",
        content: "Range shift trong uptrend:",
        options: JSON.stringify([
          { id: "opt-6-2-0", text: "RSI 40–80", isCorrect: true },
          { id: "opt-6-2-1", text: "RSI 20–60", isCorrect: false },
          { id: "opt-6-2-2", text: "RSI 0–30", isCorrect: false },
          { id: "opt-6-2-3", text: "RSI 60–100", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "RSI 40–80".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 6,
        type: "case-study",
        content: "RSI breakout giữ trên 70.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer: "Theo xu hướng; vào tại pullback; SL dưới swing.",
        explanation: "Xác nhận momentum trước entry.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 7,
        type: "multiple-choice",
        content: "Giao cắt ngược trend thường:",
        options: JSON.stringify([
          {
            id: "opt-7-2-0",
            text: "Gây nhiễu, cần confluence",
            isCorrect: true,
          },
          { id: "opt-7-2-1", text: "Là tín hiệu mạnh", isCorrect: false },
          { id: "opt-7-2-2", text: "Không cần xác nhận", isCorrect: false },
          { id: "opt-7-2-3", text: "Luôn vào lệnh ngay", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Gây nhiễu, cần confluence".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 7,
        type: "case-study",
        content: "Phân kỳ MACD tại đỉnh.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer: "Sell sau xác nhận; SL trên đỉnh; TP hỗ trợ gần.",
        explanation: "Xác nhận với nến và vùng.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 10,
        type: "multiple-choice",
        content: "Risk per trade khuyến nghị:",
        options: JSON.stringify([
          { id: "opt-10-1-0", text: "≈1%", isCorrect: true },
          { id: "opt-10-1-1", text: "≈5%", isCorrect: false },
          { id: "opt-10-1-2", text: "≈10%", isCorrect: false },
          { id: "opt-10-1-3", text: "Không cần giới hạn", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "≈1%".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 10,
        type: "case-study",
        content: "Risk budgeting tuần đã hết.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer: "Dừng giao dịch; ôn lại dữ liệu; tránh overtrade.",
        explanation: "Kỷ luật quản trị rủi ro.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 11,
        type: "multiple-choice",
        content: "FOMO trên breakout xử lý:",
        options: JSON.stringify([
          {
            id: "opt-11-1-0",
            text: "Không đuổi giá; chờ retest và xác nhận",
            isCorrect: true,
          },
          { id: "opt-11-1-1", text: "Mua đuổi ngay", isCorrect: false },
          { id: "opt-11-1-2", text: "Bỏ kế hoạch", isCorrect: false },
          { id: "opt-11-1-3", text: "Tăng khối lượng", isCorrect: false },
        ]),
        media: null,
        correct_answer: null,
        explanation: 'Đáp án đúng: "Không đuổi giá; chờ retest và xác nhận".',
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
      {
        section_id: 11,
        type: "case-study",
        content: "Chuỗi thua 5 lệnh liên tiếp.",
        options: null,
        media: JSON.stringify({
          type: "image",
          url: "https://via.placeholder.com/960x540.png?text=Case+Study",
        }),
        correct_answer:
          "Giảm risk, dừng tạm thời, xem lại hệ thống; quay lại khi tâm lý ổn định.",
        explanation: "Giữ kỷ luật cảm xúc.",
        related_question_ids: JSON.stringify([]),
        created_at: now,
        updated_at: now,
      },
    ];
    await queryInterface.bulkInsert("studies", studies);
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("studies", {});
  },
};
